{{- if .Values.auth.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "localai.fullname" . }}-secret
  labels:
    {{- include "localai.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.auth.jwtSecret | quote }}
{{- end }}
